Repository Yapp-17th/Android_2_Backend, pull requests merged in 2020-12, with the labels that each got.

#126 Fix: evaluation insert error
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
  common-module/src/main/java/com/yapp/crew/domain/model/Evaluation.java
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
  watcher-service/src/main/java/com/yapp/crew/service/WatcherService.java
Labels: bug

#127 feat: add restart shell script
  docker-compose.yml
  restart.sh
Labels: enhancement

#128 fix(board-service): change db timezone
  board-service/src/main/resources/application-dev.yml
  deploy.sh
  login-service/src/main/resources/application-dev.yml
  mypage-service/src/main/resources/application-dev.yml
Labels: hotfix

#129 fix: apply list 필드에 boardId 추가
  mypage-service/src/main/java/com/yapp/crew/model/ApplyListInfo.java
Labels: hotfix

#133 Fix:mypage history error
  mypage-service/src/main/java/com/yapp/crew/service/ApplyListService.java
  mypage-service/src/main/java/com/yapp/crew/service/CommonProfileService.java
  mypage-service/src/main/java/com/yapp/crew/service/MyProfileService.java
Labels: bug

#134 [hotfix] change validation type
  chatting-service/src/main/java/com/yapp/crew/payload/MessageRequestPayload.java
Labels: hotfix

#135 refactor: board filtering 0 값으로 할 수 있도록 수정
  board-service/src/main/java/com/yapp/crew/controller/BoardController.java
  common-module/src/main/java/com/yapp/crew/domain/repository/BoardSearchAndFilterRepository.java
Labels: hotfix

#136 [hotfix] add git pull command
  restart.sh
Labels: hotfix

#137 fix: batch -> boardRepository
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
Labels: bug

#138 fix: chatroom 찾을 수 없는 경우 exception 던지지 말고 0 으로
  mypage-service/src/main/java/com/yapp/crew/model/ApplyListInfo.java
  mypage-service/src/main/java/com/yapp/crew/service/ApplyListService.java
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
Labels: bug

#141 [deploy] setup v1.0.0-prod
  api-gateway/src/main/resources/application-prod.yml
  base-service/src/main/resources/application-prod.yml
  board-service/src/main/resources/application-prod.yml
  chat-bot-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chat-bot-service/src/main/resources/application-prod.yml
  chatting-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chatting-service/src/main/resources/application-prod.yml
  common-module/src/main/resources/application-prod.yml
  deploy.sh
  docker-compose.prod.yml
  login-service/src/main/resources/application-prod.yml
  mypage-service/src/main/resources/application-prod.yml
  watcher-service/src/main/resources/application-prod.yml
Labels: deploy

#142 [hotfix] shell script error
  deploy.sh
Labels: hotfix

#143 [hotfix] change db password
  api-gateway/src/main/resources/application-prod.yml
  base-service/src/main/resources/application-prod.yml
  board-service/src/main/resources/application-prod.yml
  chat-bot-service/src/main/resources/application-prod.yml
  chatting-service/src/main/resources/application-prod.yml
  common-module/src/main/resources/application-prod.yml
  docker-compose.prod.yml
  login-service/src/main/resources/application-prod.yml
  mypage-service/src/main/resources/application-prod.yml
  watcher-service/src/main/resources/application-prod.yml
Labels: hotfix

#144 fix: link between containers and use container name
  api-gateway/src/main/resources/application-prod.yml
Labels: bug

#145 [hotfix] change bot id
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  restart.sh
Labels: hotfix

#146 [hotfix] change db volume directory
  docker-compose.prod.yml
Labels: hotfix

#148 [hotfix] null-safe responses
  board-service/src/main/java/com/yapp/crew/model/BoardContentResponseInfo.java
  board-service/src/main/java/com/yapp/crew/model/BoardListResponseInfo.java
  board-service/src/main/java/com/yapp/crew/model/BoardStatusInfo.java
  board-service/src/main/java/com/yapp/crew/model/HostInfo.java
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chatting-service/src/main/java/com/yapp/crew/payload/ChatRoomResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  mypage-service/src/main/java/com/yapp/crew/dto/response/ApplyListResponseDto.java
  mypage-service/src/main/java/com/yapp/crew/dto/response/BookMarkListResponseDto.java
  mypage-service/src/main/java/com/yapp/crew/dto/response/EvaluateListResponseDto.java
  mypage-service/src/main/java/com/yapp/crew/dto/response/HistoryListResponseDto.java
  mypage-service/src/main/java/com/yapp/crew/dto/response/UserProfileResponseDto.java
  mypage-service/src/main/java/com/yapp/crew/model/ApplyListInfo.java
  mypage-service/src/main/java/com/yapp/crew/model/UserProfileInfo.java
  mypage-service/src/main/resources/application.yml
Labels: hotfix

#149 [hotfix] real time update type wrong value
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
Labels: hotfix

#150 Refactor: add city and category code
  board-service/src/main/java/com/yapp/crew/model/BoardContentResponseInfo.java
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
  mypage-service/src/main/java/com/yapp/crew/model/CategoryCode.java
  mypage-service/src/main/java/com/yapp/crew/model/CityCode.java
  mypage-service/src/main/java/com/yapp/crew/model/UserInfo.java
Labels: bug

#151 fix: remain count -> approve count
  board-service/src/main/java/com/yapp/crew/model/BoardListResponseInfo.java
Labels: bug

#152 [hotfix] add opponent nickname
  chatting-service/src/main/java/com/yapp/crew/payload/ChatRoomResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
Labels: hotfix

#154 Fix: user history filtering
  mypage-service/src/main/java/com/yapp/crew/service/MyProfileService.java
Labels: bug

#156 Fix: applylist chatting room link failure
  board-service/src/main/java/com/yapp/crew/model/BoardContentResponseInfo.java
  common-module/src/main/java/com/yapp/crew/domain/repository/ChatRoomRepository.java
  mypage-service/src/main/java/com/yapp/crew/service/ApplyListService.java
Labels: board-service, bug

#158 [hotfix] chat room exit issue
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/model/ChatRoom.java
  docs/README.md
  docs/architecture.md
  docs/database.md
  mypage-service/src/main/java/com/yapp/crew/model/ApplyListInfo.java
  mypage-service/src/main/java/com/yapp/crew/service/ApplyListService.java
Labels: hotfix

#159 [hotfix] change token header name
  login-service/src/main/java/com/yapp/crew/service/TokenService.java
Labels: hotfix

#160 feat: add user id header
  login-service/src/main/java/com/yapp/crew/service/TokenService.java
Labels: hotfix

#161 style: board status show style
  common-module/src/main/java/com/yapp/crew/domain/status/BoardStatus.java
Labels: hotfix

#162 feat: add intro field in board content
  board-service/src/main/java/com/yapp/crew/model/HostInfo.java
Labels: hotfix

#163 [hotfix] fix timestamp to datetime
  init.sql
Labels: database

#166 [hotfix] apply list chat room issue
  mypage-service/src/main/java/com/yapp/crew/service/ApplyListService.java
Labels: hotfix

#167 [hotfix] block chatroom create if my post
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/errors/CannotApplyToMyBoardException.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
Labels: chat-service, hotfix

#168 fix: watcher에서 evaluation insert할 때 host id 추가
  mypage-service/src/main/java/com/yapp/crew/service/EvaluateService.java
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
Labels: bug

#169 feat: create custom handshake interceptor
  chatting-service/src/main/java/com/yapp/crew/config/WebSocketConfig.java
  chatting-service/src/main/java/com/yapp/crew/websocket/CustomHandshakeInterceptor.java
  common-module/src/main/java/com/yapp/crew/auth/Auth.java
  common-module/src/main/java/com/yapp/crew/domain/errors/TokenRequiredException.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
Labels: chat-service, hotfix

#170 fix: add kafka log retention time options
  docker-compose.prod.yml
  docker-compose.yml
Labels: chat-service, hotfix

#172 refactor: exercise, city, tag 필드를 객체 형태로 전달
  board-service/src/main/java/com/yapp/crew/model/BoardContentResponseInfo.java
  board-service/src/main/java/com/yapp/crew/model/CategoryCode.java
  board-service/src/main/java/com/yapp/crew/model/CityCode.java
  board-service/src/main/java/com/yapp/crew/model/TagCode.java
Labels: hotfix

#173 fix: register custom handshake interceptor
  chatting-service/src/main/java/com/yapp/crew/config/WebSocketConfig.java
Labels: hotfix

#175 refactor: date to localdatetime
  board-service/src/main/java/com/yapp/crew/model/BoardContentResponseInfo.java
Labels: hotfix

#174 fix: disable handshake interceptor
  chatting-service/src/main/java/com/yapp/crew/config/WebSocketConfig.java
Labels: chat-service, hotfix

#177 fix: add user exit field
  chatting-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  restart.sh
Labels: hotfix

#178 fix: read unread message when calling chat messages
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/repository/MessageRepository.java
Labels: chat-service, hotfix

#179 fix: check if unread message exists
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
Labels: chat-service, hotfix

#171 hotfix: auto manage member access
  api-gateway/src/main/java/com/yapp/crew/filters/AuthenticationFilter.java
  board-service/src/main/java/com/yapp/crew/service/ReportService.java
  common-module/src/main/java/com/yapp/crew/domain/errors/ForbiddenUserSignUpException.java
  common-module/src/main/java/com/yapp/crew/domain/model/User.java
  common-module/src/main/java/com/yapp/crew/domain/repository/UserRepository.java
  common-module/src/main/java/com/yapp/crew/domain/status/UserStatus.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
  init.sql
  login-service/src/main/java/com/yapp/crew/service/SignInService.java
  schema.sql
  watcher-service/src/main/java/com/yapp/crew/service/UserAuthenticationService.java
  watcher-service/src/main/java/com/yapp/crew/service/WatcherService.java
Labels: board-service

#182 cleanup dependencies
  api-gateway/Dockerfile
  api-gateway/build.gradle
  base-service/Dockerfile
  base-service/build.gradle
  base-service/src/main/java/com/yapp/crew/utils/EnumToList.java
  board-service/Dockerfile
  board-service/build.gradle
  chat-bot-service/Dockerfile
  chat-bot-service/build.gradle
  chatting-service/Dockerfile
  chatting-service/build.gradle
  common-module/build.gradle
  common-module/src/main/java/com/yapp/crew/domain/condition/BoardFilterCondition.java
  deploy.sh
  login-service/Dockerfile
  login-service/build.gradle
  mypage-service/Dockerfile
  mypage-service/build.gradle
  restart.sh
  watcher-service/Dockerfile
  watcher-service/build.gradle
Labels: cleanup

#189 fix: board complete message type
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  common-module/src/main/java/com/yapp/crew/domain/type/MessageType.java
Labels: chat-bot-service, hotfix

#192 feat: message bulk update by websocket
  chatting-service/build.gradle
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/repository/MessageRepository.java
Labels: chat-service, enhancement

#197 fix: add update message type
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/type/MessageType.java
Labels: chat-service, hotfix

#198 fix: update query 개선
  init.sql
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
  watcher-service/src/main/java/com/yapp/crew/service/UserAuthenticationService.java
  watcher-service/src/main/java/com/yapp/crew/service/WatcherService.java
  watcher-service/src/main/resources/application-dev.yml
  watcher-service/src/main/resources/application-prod.yml
  watcher-service/src/main/resources/application.yml
Labels: hotfix

#200 fix: send my messages to my chat room list
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
Labels: chat-service, hotfix

#201 fix: read both guest and host
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/model/Message.java
Labels: chat-service, hotfix

#202 fix: remove volumes at deploy
  deploy.sh
Labels: deploy, hotfix

#203 feat: add docker container restart policy
  docker-compose.prod.yml
Labels: enhancement

#204 Refactor: cleanup stream filters
  common-module/src/main/java/com/yapp/crew/domain/condition/HistoryCondition.java
  common-module/src/main/java/com/yapp/crew/domain/repository/BoardRepository.java
  common-module/src/main/java/com/yapp/crew/domain/repository/UserProfileHistoryRepository.java
  common-module/src/main/java/com/yapp/crew/domain/type/HistoryType.java
  login-service/src/main/java/com/yapp/crew/service/SignUpService.java
  mypage-service/src/main/java/com/yapp/crew/controller/CommonProfileController.java
  mypage-service/src/main/java/com/yapp/crew/controller/MyProfileController.java
  mypage-service/src/main/java/com/yapp/crew/dto/response/HistoryListResponseDto.java
  mypage-service/src/main/java/com/yapp/crew/service/CommonProfileService.java
  mypage-service/src/main/java/com/yapp/crew/service/MyProfileService.java
  watcher-service/src/main/java/com/yapp/crew/service/WatcherService.java
Labels: cleanup

#205 fix: update 해야하는 board status 변경
  common-module/src/main/java/com/yapp/crew/domain/repository/BoardRepository.java
  watcher-service/src/main/java/com/yapp/crew/service/WatcherService.java
Labels: bug, hotfix

#207 Refactor: modify enum value
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/status/BoardStatus.java
  login-service/src/main/java/com/yapp/crew/service/SignUpService.java
Labels: cleanup

#208 feat: auto login 추가
  login-service/src/main/java/com/yapp/crew/config/JwtUtils.java
  login-service/src/main/java/com/yapp/crew/controller/SignInController.java
  login-service/src/main/java/com/yapp/crew/service/SignInService.java
  login-service/src/main/java/com/yapp/crew/service/TokenService.java
Labels: enhancement

#209 fix: query param 한글 디코딩 추가
  common-module/src/main/java/com/yapp/crew/domain/condition/BoardSearchCondition.java
Labels: bug

#210 fix: 검색 조건에 게시판 제목, 내용, 닉네임 추가 및 or 조건으로 변경
  common-module/src/main/java/com/yapp/crew/domain/repository/BoardSearchAndFilterRepository.java
Labels: board-service
