Repository Yapp-17th/Android_2_Backend, pull requests merged in 2020-11, with the labels that each got.

#20 refactor: bookmark, user-exercise entity 추가
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
  common-module/src/main/java/com/yapp/crew/domain/model/BookMark.java
  common-module/src/main/java/com/yapp/crew/domain/model/Category.java
  common-module/src/main/java/com/yapp/crew/domain/model/Evaluation.java
  common-module/src/main/java/com/yapp/crew/domain/model/HiddenBoard.java
  common-module/src/main/java/com/yapp/crew/domain/model/User.java
  common-module/src/main/java/com/yapp/crew/domain/model/UserExercise.java
  common-module/src/main/java/com/yapp/crew/domain/repository/BookMarkRepository.java
  common-module/src/main/java/com/yapp/crew/domain/repository/EvaluationRepository.java
  common-module/src/main/java/com/yapp/crew/domain/repository/HiddenBoardRepository.java
  common-module/src/main/java/com/yapp/crew/domain/repository/UserExerciseRepository.java
  common-module/src/main/java/com/yapp/crew/domain/status/UserStatus.java
  login-api/src/main/java/com/yapp/crew/dto/SignUpRequestDto.java
  login-api/src/main/java/com/yapp/crew/model/SignupUserInfo.java
  login-api/src/main/java/com/yapp/crew/service/SignUpService.java
Labels: cleanup, enhancement

#28 feat: 게시판 api 구현
  base-api/src/main/resources/application-dev.yml
  base-api/src/main/resources/application.yml
  board-api/build.gradle
  board-api/src/main/java/com/yapp/crew/controller/BoardController.java
  board-api/src/main/java/com/yapp/crew/controller/BookmarkController.java
  board-api/src/main/java/com/yapp/crew/controller/HiddenBoardController.java
  board-api/src/main/java/com/yapp/crew/controller/ReportController.java
  board-api/src/main/java/com/yapp/crew/controller/SearchController.java
  board-api/src/main/java/com/yapp/crew/dto/BoardContentResponseDto.java
  board-api/src/main/java/com/yapp/crew/dto/BoardFilterRequestDto.java
  board-api/src/main/java/com/yapp/crew/dto/BoardIdRequestDto.java
  board-api/src/main/java/com/yapp/crew/dto/BoardListResponseDto.java
  board-api/src/main/java/com/yapp/crew/dto/BoardReportRequestDto.java
  board-api/src/main/java/com/yapp/crew/dto/BoardRequestDto.java
  board-api/src/main/java/com/yapp/crew/dto/SimpleResponseDto.java
  board-api/src/main/java/com/yapp/crew/exception/InactiveUserException.java
  board-api/src/main/java/com/yapp/crew/exception/InternalServerErrorException.java
  board-api/src/main/java/com/yapp/crew/exception/InvalidRequestBodyException.java
  board-api/src/main/java/com/yapp/crew/exception/SuspendedUserException.java
  board-api/src/main/java/com/yapp/crew/exception/WrongTokenException.java
  board-api/src/main/java/com/yapp/crew/model/BoardContentResponseInfo.java
  board-api/src/main/java/com/yapp/crew/model/BoardFilter.java
  board-api/src/main/java/com/yapp/crew/model/BoardPostRequiredInfo.java
  board-api/src/main/java/com/yapp/crew/model/BoardReport.java
  board-api/src/main/java/com/yapp/crew/model/BoardResponseInfo.java
  board-api/src/main/java/com/yapp/crew/model/HostInfo.java
  board-api/src/main/java/com/yapp/crew/model/SimpleResponse.java
  board-api/src/main/java/com/yapp/crew/service/BoardService.java
  board-api/src/main/java/com/yapp/crew/service/BookMarkService.java
  board-api/src/main/java/com/yapp/crew/service/HiddenBoardService.java
  board-api/src/main/java/com/yapp/crew/service/ReportService.java
  board-api/src/main/java/com/yapp/crew/utils/ResponseMessage.java
  board-api/src/main/resources/application-dev.yml
  board-api/src/main/resources/application.yml
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
  common-module/src/main/java/com/yapp/crew/domain/model/BookMark.java
  common-module/src/main/java/com/yapp/crew/domain/model/HiddenBoard.java
  common-module/src/main/java/com/yapp/crew/domain/model/User.java
  common-module/src/main/java/com/yapp/crew/domain/repository/BoardRepository.java
  common-module/src/main/java/com/yapp/crew/domain/repository/BookMarkRepository.java
  common-module/src/main/java/com/yapp/crew/domain/repository/TagRepository.java
  login-api/src/main/java/com/yapp/crew/controller/SignInController.java
  login-api/src/main/java/com/yapp/crew/controller/SignUpController.java
  login-api/src/main/java/com/yapp/crew/controller/WithdrawController.java
Labels: board-service, enhancement

#32 [feat] 신청한 사용자 승인하는 api 구현
  chat-bot-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/java/com/yapp/crew/json/BotMessages.java
  chat-bot-service/src/main/java/com/yapp/crew/payload/ApproveRequestPayload.java
  chat-bot-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application.yml
  chat-bot-service/src/main/resources/bot-messages.json
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingExceptionHandler.java
  chatting-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chatting-service/src/main/java/com/yapp/crew/payload/ApproveRequestPayload.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingProducerService.java
  chatting-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/application.yml
  common-module/src/main/java/com/yapp/crew/domain/errors/AlreadyApprovedException.java
  common-module/src/main/java/com/yapp/crew/domain/errors/GuestApplyNotFoundException.java
  common-module/src/main/java/com/yapp/crew/domain/errors/WrongGuestException.java
  common-module/src/main/java/com/yapp/crew/domain/errors/WrongHostException.java
  common-module/src/main/java/com/yapp/crew/domain/model/AppliedUser.java
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
  common-module/src/main/java/com/yapp/crew/domain/model/Message.java
  common-module/src/main/java/com/yapp/crew/domain/model/User.java
  common-module/src/main/java/com/yapp/crew/domain/repository/AppliedUserRepository.java
Labels: chat-bot-service, chat-service, enhancement

#34 [cleanup] 채팅 & 챗봇 서비스 클린업 작업
  chat-bot-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/java/com/yapp/crew/controller/ChatBotExceptionHandler.java
  chat-bot-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chat-bot-service/src/main/java/com/yapp/crew/payload/GuidelineRequestPayload.java
  chat-bot-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application.yml
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingExceptionHandler.java
  chatting-service/src/main/java/com/yapp/crew/json/BotMessages.java
  chatting-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chatting-service/src/main/java/com/yapp/crew/payload/ChatRoomResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/GuidelineRequestPayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingProducerService.java
  chatting-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/application.yml
  chatting-service/src/main/resources/bot-messages.json
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
Labels: cleanup

#37 [minor-fix] @ConfigurationProperties Prefix 제거
  chat-bot-service/src/main/java/com/yapp/crew/json/BotMessages.java
Labels: bug, minor-fix

#40 [hotfix] 신청한 사용자(applied user) 생성 로직을 챗봇 서비스에서 수행하기
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/java/com/yapp/crew/controller/ChatBotExceptionHandler.java
  chat-bot-service/src/main/java/com/yapp/crew/json/BotMessages.java
  chat-bot-service/src/main/resources/bot-messages.json
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingExceptionHandler.java
  chatting-service/src/main/java/com/yapp/crew/payload/ChatRoomResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingProducerService.java
  common-module/src/main/java/com/yapp/crew/domain/errors/AlreadyAppliedException.java
  common-module/src/main/java/com/yapp/crew/domain/errors/NoSpaceToApplyException.java
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
  common-module/src/main/java/com/yapp/crew/domain/model/Message.java
  common-module/src/main/java/com/yapp/crew/domain/model/ProfileMessage.java
  common-module/src/main/java/com/yapp/crew/domain/model/User.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
Labels: bug, chat-bot-service, hotfix

#41 [minor-fix] reformat code
  chat-bot-service/build.gradle
  chat-bot-service/src/main/java/com/yapp/crew/config/ChatBotConsumerConfig.java
  chat-bot-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/java/com/yapp/crew/controller/ChatBotExceptionHandler.java
  chat-bot-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chat-bot-service/src/main/java/com/yapp/crew/producer/ChatBotProducer.java
  chatting-service/build.gradle
  chatting-service/src/main/java/com/yapp/crew/ChattingServiceApplication.java
  chatting-service/src/main/java/com/yapp/crew/config/ChattingConsumerConfig.java
  chatting-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chatting-service/src/main/java/com/yapp/crew/config/WebSocketConfig.java
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingExceptionHandler.java
  chatting-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chatting-service/src/main/java/com/yapp/crew/payload/ApproveRequestPayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/ChatRoomRequestPayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/ChatRoomResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageRequestPayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingProducerService.java
Labels: bug, minor-fix

#44 [feat] 채팅 메시지 udpate / response -> ok
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/java/com/yapp/crew/controller/ChatBotExceptionHandler.java
  chat-bot-service/src/main/java/com/yapp/crew/producer/ChatBotProducer.java
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingExceptionHandler.java
  chatting-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingProducerService.java
  common-module/src/main/java/com/yapp/crew/domain/errors/MessageNotFoundException.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
  common-module/src/main/java/com/yapp/crew/network/model/SimpleResponse.java
Labels: enhancement

#45 [feat] applied status -> pending, applied, approved 추가
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chatting-service/src/main/java/com/yapp/crew/network/HttpResponseBody.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingProducerService.java
  common-module/src/main/java/com/yapp/crew/domain/model/AppliedUser.java
  common-module/src/main/java/com/yapp/crew/domain/status/AppliedStatus.java
Labels: minor-fix

#46 [hotfix] 채팅 조회시 appliedStatus를 호스트와 게스트를 구분해서 조회
  chatting-service/src/main/java/com/yapp/crew/service/ChattingProducerService.java
Labels: bug, hotfix

#49 fix: board 시간 보여주는 부분 추가
  board-api/src/main/java/com/yapp/crew/model/BoardContentResponseInfo.java
  board-api/src/main/java/com/yapp/crew/model/BoardListResponseInfo.java
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
Labels: bug

#54 [hotfix} change real time update type to approved
  chat-bot-service/src/main/resources/application-dev.yml
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  chatting-service/src/main/resources/application-dev.yml
  watcher-service/src/main/resources/application-dev.yml
Labels: bug, hotfix

#55 [hotfix] change payload to response payload
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
Labels: bug, hotfix

#56 [hotfix] create custom property source factory
  chat-bot-service/src/main/java/com/yapp/crew/json/BotMessages.java
  chat-bot-service/src/main/java/com/yapp/crew/json/JsonPropertySourceFactory.java
Labels: bug, hotfix

#57 [feat] 게시글 삭제 시 -> 활동 취소 봇 메시지 전송
  board-api/build.gradle
  board-api/src/main/java/com/yapp/crew/controller/BoardController.java
  board-api/src/main/java/com/yapp/crew/model/BoardCancel.java
  board-api/src/main/java/com/yapp/crew/producer/BoardProducer.java
  board-api/src/main/java/com/yapp/crew/service/BoardService.java
  board-api/src/main/resources/application-dev.yml
  board-api/src/main/resources/application.yml
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/java/com/yapp/crew/json/BotMessages.java
  chat-bot-service/src/main/java/com/yapp/crew/payload/BoardCanceledPayload.java
  chat-bot-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application.yml
  chat-bot-service/src/main/resources/bot-messages.json
Labels: board-service, chat-bot-service, enhancement

#63 [feat] create zuul api gateway
  api-gateway/Dockerfile
  api-gateway/build.gradle
  api-gateway/src/main/java/com/yapp/crew/ApiGatewayApplication.java
  api-gateway/src/main/java/com/yapp/crew/auth/Auth.java
  api-gateway/src/main/java/com/yapp/crew/errors/InactiveUserException.java
  api-gateway/src/main/java/com/yapp/crew/errors/SuspendedUserException.java
  api-gateway/src/main/java/com/yapp/crew/errors/TokenRequiredException.java
  api-gateway/src/main/java/com/yapp/crew/errors/UserNotFoundException.java
  api-gateway/src/main/java/com/yapp/crew/errors/WrongTokenPrefixException.java
  api-gateway/src/main/java/com/yapp/crew/filters/AuthenticationFilter.java
  api-gateway/src/main/java/com/yapp/crew/handlers/ExceptionHandler.java
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application.yml
  base-api/src/main/resources/application-dev.yml
  base-api/src/main/resources/application.yml
  board-api/src/main/java/com/yapp/crew/config/AuthInterceptor.java
  board-api/src/main/java/com/yapp/crew/config/WebConfiguration.java
  board-api/src/main/java/com/yapp/crew/controller/BoardController.java
  board-api/src/main/java/com/yapp/crew/controller/BookmarkController.java
  board-api/src/main/java/com/yapp/crew/controller/HiddenBoardController.java
  board-api/src/main/java/com/yapp/crew/controller/ReportController.java
  board-api/src/main/java/com/yapp/crew/controller/SearchController.java
  board-api/src/main/java/com/yapp/crew/service/BookMarkService.java
  board-api/src/main/java/com/yapp/crew/service/HiddenBoardService.java
  board-api/src/main/java/com/yapp/crew/service/ReportService.java
  board-api/src/main/resources/application-dev.yml
  board-api/src/main/resources/application.yml
  chat-bot-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application.yml
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  chatting-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/application.yml
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
  login-api/src/main/resources/application-dev.yml
  login-api/src/main/resources/application.yml
  mypage-api/src/main/java/com/yapp/crew/config/AuthInterceptor.java
  mypage-api/src/main/java/com/yapp/crew/config/WebConfiguration.java
  mypage-api/src/main/java/com/yapp/crew/controller/ApplyListController.java
  mypage-api/src/main/java/com/yapp/crew/controller/BookMarkController.java
  mypage-api/src/main/java/com/yapp/crew/controller/CommonProfileController.java
  mypage-api/src/main/java/com/yapp/crew/controller/EvaluateController.java
  mypage-api/src/main/java/com/yapp/crew/controller/MyProfileController.java
  mypage-api/src/main/java/com/yapp/crew/service/ApplyListService.java
  mypage-api/src/main/resources/application-dev.yml
  mypage-api/src/main/resources/application.yml
  settings.gradle
  watcher-service/src/main/resources/application-dev.yml
  watcher-service/src/main/resources/application.yml
Labels: enhancement

#64 [hotfix] rollback suspended inactive user exception
  board-api/src/main/java/com/yapp/crew/controller/BoardController.java
  common-module/src/main/java/com/yapp/crew/domain/errors/TokenRequiredException.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
Labels: hotfix

#68 [feat] 채팅방 목록으로 실시간 메시지 전송
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
Labels: chat-service, enhancement

#70 fix: user email null pointer error
  mypage-service/src/main/java/com/yapp/crew/model/UserUpdateRequest.java
Labels: hotfix

#71 [deploy] v1.0.0-beta
  api-gateway/src/main/resources/application-dev.yml
  base-service/Dockerfile
  base-service/src/main/resources/application-dev.yml
  board-service/Dockerfile
  board-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/application-dev.yml
  common-module/src/main/resources/application-dev.yml
  login-service/Dockerfile
  login-service/src/main/resources/application-dev.yml
  mypage-service/Dockerfile
  mypage-service/src/main/resources/application-dev.yml
Labels: deploy

#72 [hotfix] rollback gradlew
  .gitignore
  gradlew
  gradlew.bat
Labels: hotfix

#73 [hotfix] rollback gradle wrapper
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: hotfix

#74 [hotfix] update docker-compose / application.yml
  api-gateway/src/main/java/com/yapp/crew/filters/AuthenticationFilter.java
  api-gateway/src/main/resources/application-dev.yml
  base-service/src/main/resources/application-dev.yml
  board-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/application-dev.yml
  common-module/src/main/resources/application-dev.yml
  docker-compose.yml
  login-service/src/main/resources/application-dev.yml
  mypage-service/src/main/resources/application-dev.yml
Labels: hotfix

#78 [hotfix] change subscribe endpoint
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
Labels: hotfix

#81 [hotfix] send to host & guest if sender is bot
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
Labels: bug, hotfix

#82 [feat] create deploy script
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application.yml
  base-service/src/main/resources/application-dev.yml
  base-service/src/main/resources/application.yml
  board-service/src/main/resources/application-dev.yml
  board-service/src/main/resources/application.yml
  chat-bot-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application.yml
  chatting-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/application.yml
  common-module/src/main/resources/application-dev.yml
  common-module/src/main/resources/application.yml
  deploy.sh
  login-service/src/main/resources/application-dev.yml
  login-service/src/main/resources/application.yml
  mypage-service/src/main/resources/application-dev.yml
  mypage-service/src/main/resources/application.yml
  watcher-service/src/main/resources/application-dev.yml
  watcher-service/src/main/resources/application.yml
Labels: deploy

#83 [hotfix] add gradlew command
  deploy.sh
Labels: hotfix

#80 Fix:db exception handling
  base-service/src/main/java/com/yapp/crew/controller/AddressListController.java
  base-service/src/main/java/com/yapp/crew/controller/BoardReportTypeListController.java
  base-service/src/main/java/com/yapp/crew/controller/ExerciseListController.java
  base-service/src/main/java/com/yapp/crew/controller/UserReportTypeListController.java
  base-service/src/main/java/com/yapp/crew/controller/UserTagListController.java
  base-service/src/main/java/com/yapp/crew/dto/EnumListResponseDto.java
  base-service/src/test/java/com/yapp/crew/controller/AddressListControllerTest.java
  base-service/src/test/java/com/yapp/crew/controller/ExerciseListControllerTest.java
  board-service/src/main/java/com/yapp/crew/dto/request/BoardInfoRequestDto.java
  board-service/src/main/java/com/yapp/crew/service/BoardService.java
  common-module/src/main/java/com/yapp/crew/domain/model/Board.java
  common-module/src/main/java/com/yapp/crew/domain/model/User.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
  login-service/src/main/java/com/yapp/crew/dto/request/SignUpRequestDto.java
  mypage-service/src/main/java/com/yapp/crew/dto/request/UserReportRequestDto.java
  mypage-service/src/main/java/com/yapp/crew/dto/request/UserUpdateRequestDto.java
Labels: bug

#84 [hotfix] change guideline message
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/resources/bot-messages.json
  common-module/src/main/java/com/yapp/crew/domain/type/MessageType.java
Labels: hotfix

#85 [hotfix] fix to nullable=false & fetchtype=eager
  common-module/src/main/java/com/yapp/crew/domain/model/BookMark.java
  common-module/src/main/java/com/yapp/crew/domain/model/Evaluation.java
  common-module/src/main/java/com/yapp/crew/domain/model/HiddenBoard.java
  common-module/src/main/java/com/yapp/crew/domain/model/User.java
  common-module/src/main/java/com/yapp/crew/domain/model/UserExercise.java
Labels: hotfix

#86 [feat] count messages by chatroom
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageResponsePayload.java
  common-module/src/main/java/com/yapp/crew/domain/model/Message.java
  common-module/src/main/java/com/yapp/crew/domain/repository/MessageRepository.java
Labels: chat-service, enhancement

#87 [hotfix] change to message id
  common-module/src/main/java/com/yapp/crew/domain/model/ChatRoom.java
Labels: hotfix

#89 [feat] exit chat room api
  chat-bot-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/java/com/yapp/crew/json/BotMessages.java
  chat-bot-service/src/main/java/com/yapp/crew/payload/UserExitedPayload.java
  chat-bot-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/application.yml
  chat-bot-service/src/main/resources/bot-messages.json
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/payload/ChatRoomResponsePayload.java
  chatting-service/src/main/java/com/yapp/crew/payload/UserExitedPayload.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  chatting-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/application.yml
  common-module/src/main/java/com/yapp/crew/domain/model/ChatRoom.java
  common-module/src/main/java/com/yapp/crew/domain/repository/ChatRoomRepository.java
  common-module/src/main/java/com/yapp/crew/domain/type/RealTimeUpdateType.java
Labels: chat-bot-service, chat-service, enhancement

#91 [hotfix] select active chat rooms
  common-module/src/main/java/com/yapp/crew/domain/repository/ChatRoomRepository.java
Labels: hotfix

#93 [hotfix] resolve chat room exit issues
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/errors/AlreadyExitedException.java
  common-module/src/main/java/com/yapp/crew/domain/errors/CannotApplyException.java
  common-module/src/main/java/com/yapp/crew/domain/errors/CannotApproveException.java
  common-module/src/main/java/com/yapp/crew/domain/errors/CannotDisapproveException.java
  common-module/src/main/java/com/yapp/crew/domain/repository/ChatRoomRepository.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
Labels: bug, hotfix

#94 fix: Long to int compile error
  mypage-service/src/main/java/com/yapp/crew/service/EvaluateService.java
Labels: bug

#98 [hotfix] block actions if board is finished or canceled
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
Labels: hotfix

#103 refactor: user like/dislike method 하나로
  common-module/src/main/java/com/yapp/crew/domain/model/Evaluation.java
  common-module/src/main/java/com/yapp/crew/domain/repository/BoardSearchAndFilterRepository.java
  mypage-service/src/main/java/com/yapp/crew/service/EvaluateService.java
Labels: bug, cleanup

#102 [deploy] setup log system - elastic stack
  .gitignore
  api-gateway/Dockerfile
  api-gateway/build.gradle
  api-gateway/src/main/resources/logback-spring.xml
  base-service/Dockerfile
  base-service/build.gradle
  board-service/Dockerfile
  board-service/build.gradle
  board-service/src/main/resources/logback-spring.xml
  chat-bot-service/Dockerfile
  chat-bot-service/build.gradle
  chat-bot-service/src/main/resources/logback-spring.xml
  chatting-service/Dockerfile
  chatting-service/build.gradle
  chatting-service/src/main/resources/logback-spring.xml
  docker-compose.yml
  filebeat/filebeat.docker.yml
  init.sql
  login-service/Dockerfile
  login-service/build.gradle
  login-service/src/main/resources/logback-spring.xml
  logstash/pipeline/logstash.conf
  mypage-service/Dockerfile
  mypage-service/build.gradle
  mypage-service/src/main/resources/logback-spring.xml
  watcher-service/Dockerfile
Labels: deploy, don't merge

#105 [deploy] refactor elk settings
  .gitignore
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/logback-spring.xml
  api-gateway/src/main/resources/logback.xml
  board-service/src/main/resources/application-dev.yml
  board-service/src/main/resources/logback-spring.xml
  board-service/src/main/resources/logback.xml
  chat-bot-service/src/main/resources/application-dev.yml
  chat-bot-service/src/main/resources/logback-spring.xml
  chat-bot-service/src/main/resources/logback.xml
  chatting-service/src/main/resources/application-dev.yml
  chatting-service/src/main/resources/logback-spring.xml
  chatting-service/src/main/resources/logback.xml
  deploy.sh
  docker-compose.yml
  filebeat/filebeat.docker.yml
  login-service/src/main/resources/logback-spring.xml
  login-service/src/main/resources/logback.xml
  logstash/pipeline/logstash.conf
  mypage-service/src/main/resources/logback-spring.xml
  mypage-service/src/main/resources/logback.xml
  watcher-service/src/main/resources/application-dev.yml
  watcher-service/src/main/resources/logback.xml
Labels: deploy, enhancement

#108 [hotfix] resolve illegal reflective access issue
  api-gateway/build.gradle
  base-service/build.gradle
  board-service/build.gradle
  chat-bot-service/build.gradle
  chat-bot-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  chatting-service/build.gradle
  chatting-service/src/main/java/com/yapp/crew/config/KafkaTopicConfig.java
  docker-compose.yml
  login-service/build.gradle
  mypage-service/build.gradle
  watcher-service/build.gradle
Labels: bug, hotfix

#109 [hotfix] remove devtools dependency
  api-gateway/build.gradle
  base-service/build.gradle
  board-service/build.gradle
  chat-bot-service/build.gradle
  chatting-service/build.gradle
  common-module/build.gradle
  docker-compose.yml
  login-service/build.gradle
  mypage-service/build.gradle
  watcher-service/build.gradle
Labels: bug, hotfix

#110 [hotfix] config logback-spring.xml
  api-gateway/src/main/resources/logback-spring.xml
  api-gateway/src/main/resources/logback.xml
  board-service/src/main/resources/logback-spring.xml
  board-service/src/main/resources/logback.xml
  chat-bot-service/src/main/resources/logback-spring.xml
  chat-bot-service/src/main/resources/logback.xml
  chatting-service/src/main/resources/logback-spring.xml
  chatting-service/src/main/resources/logback.xml
  login-service/src/main/resources/logback-spring.xml
  login-service/src/main/resources/logback.xml
  mypage-service/src/main/resources/logback-spring.xml
  mypage-service/src/main/resources/logback.xml
Labels: bug, hotfix

#111 fix: build에서 dto를 model로 바꾸는 부분 오류 수정
  common-module/src/main/java/com/yapp/crew/domain/errors/ReportCodeNotFoundException.java
  common-module/src/main/java/com/yapp/crew/domain/type/ReportType.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
  mypage-service/src/main/java/com/yapp/crew/model/UserReportRequest.java
  mypage-service/src/main/java/com/yapp/crew/service/EvaluateService.java
Labels: bug

#114 [hotfix] add logback encoder dependency
  base-service/build.gradle
Labels: hotfix

#115 [cleanup] watcher-service 추가 + 로그 추가
  api-gateway/src/main/java/com/yapp/crew/filters/PostFilter.java
  api-gateway/src/main/java/com/yapp/crew/handlers/ExceptionHandler.java
  api-gateway/src/main/resources/application-dev.yml
  api-gateway/src/main/resources/application.yml
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/producer/ChattingProducer.java
  docker-compose.yml
  watcher-service/build.gradle
  watcher-service/src/main/java/com/yapp/crew/producer/WatcherProducer.java
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
  watcher-service/src/main/java/com/yapp/crew/service/WatcherService.java
  watcher-service/src/main/resources/logback-spring.xml
  watcher-service/src/main/resources/logback.xml
Labels: cleanup

#116 [hotfix] change watcher-service db address
  api-gateway/src/main/java/com/yapp/crew/handlers/ExceptionHandler.java
  watcher-service/src/main/resources/application-dev.yml
Labels: hotfix

#117 refactor: board list에 recruit number 추가
  board-service/src/main/java/com/yapp/crew/model/BoardListResponseInfo.java
Labels: board-service

#119 [hotfix] add @Transactional
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
  watcher-service/src/main/java/com/yapp/crew/service/WatcherService.java
Labels: hotfix

#121 [hotfix] change profile message content
  chat-bot-service/src/main/java/com/yapp/crew/consumer/ChatBotConsumer.java
  chat-bot-service/src/main/resources/bot-messages.json
Labels: hotfix

#122 [feat] add healthcheck
  api-gateway/src/main/java/com/yapp/crew/controller/HealthChecker.java
  base-service/src/main/java/com/yapp/crew/controller/HealthChecker.java
  board-service/src/main/java/com/yapp/crew/controller/HealthChecker.java
  chat-bot-service/src/main/java/com/yapp/crew/controller/HealthChecker.java
  chatting-service/src/main/java/com/yapp/crew/controller/HealthChecker.java
  docker-compose.yml
  login-service/src/main/java/com/yapp/crew/controller/HealthChecker.java
  mypage-service/src/main/java/com/yapp/crew/controller/HealthChecker.java
  watcher-service/src/main/java/com/yapp/crew/controller/HealthChecker.java
Labels: enhancement

#123 Fix: board batch insert evaluation
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
  watcher-service/src/main/java/com/yapp/crew/service/BoardBatchService.java
Labels: bug

#124 [feat] add message interceptor
  chatting-service/src/main/java/com/yapp/crew/config/WebSocketConfig.java
  chatting-service/src/main/java/com/yapp/crew/consumer/ChattingConsumer.java
  chatting-service/src/main/java/com/yapp/crew/controller/ChattingController.java
  chatting-service/src/main/java/com/yapp/crew/payload/MessageRequestPayload.java
  common-module/build.gradle
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
  deploy.sh
Labels: enhancement

#125 [hotfix] add exception handlers
  chatting-service/src/main/java/com/yapp/crew/service/ChattingService.java
  common-module/src/main/java/com/yapp/crew/domain/type/ResponseType.java
  common-module/src/main/java/com/yapp/crew/network/handler/CommonExceptionHandler.java
Labels: hotfix
